import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import {
  AlertTriangle,
  Play,
  RefreshCw,
  Server,
  ShieldAlert,
  Square,
  Terminal,
  Trash2,
  Wifi,
  Wrench,
  Zap,
} from 'lucide-react';
import { k8sApi, subscriberApi } from '../api';
import { UeTrafficMonitor } from '../components/common/UeTrafficMonitor';
import type {
  K8sLabAction,
  K8sCommandDefinition,
  K8sLabStatus,
  K8sLogFile,
  K8sScriptResult,
  K8sUeScenario,
  K8sUeScriptAction,
  SubscriberUeState,
  SubscriberUeStatus,
} from '../types';

const SCENARIO_OPTIONS: Array<{ value: K8sUeScenario; label: string }> = [
  { value: 'normal', label: 'Normal' },
  { value: 'auth-error', label: 'Auth Error' },
  { value: 'dnn-error', label: 'DNN Error' },
  { value: 'imsi-error', label: 'IMSI Error' },
  { value: 'slice-error', label: 'Slice Error' },
];

const LAB_ACTIONS: Array<{
  action: K8sLabAction;
  label: string;
  description: string;
  tone: 'primary' | 'danger' | 'ghost';
  confirmText?: string;
}> = [
  {
    action: 'start-lab',
    label: 'Start 5GSA Lab',
    description: 'Runs START_5gsa.sh from the sibling LAAS repository.',
    tone: 'primary',
  },
  {
    action: 'stop-lab',
    label: 'Stop 5GSA Lab',
    description: 'Runs STOP_5gsa.sh and deletes the Open5GS namespace resources.',
    tone: 'danger',
    confirmText: 'Stop the 5GSA lab and remove deployed resources?',
  },
  {
    action: 'install-node',
    label: 'Install K8s Node',
    description: 'Runs INSTALL_NODE_k8s.sh on the host. This is long-running and modifies the VM.',
    tone: 'ghost',
    confirmText: 'Install Kubernetes, Cilium, Multus, and observability tooling on this host?',
  },
  {
    action: 'delete-node',
    label: 'Delete K8s Node',
    description: 'Runs DELETE_NODE_k8s.sh. This is destructive and removes cluster packages.',
    tone: 'danger',
    confirmText: 'Delete the Kubernetes node and remove installed cluster tooling from this host?',
  },
];

const UE_ACTIONS: Array<{
  action: K8sUeScriptAction;
  label: string;
  description: string;
  tone: 'primary' | 'danger' | 'ghost';
  confirmText?: string;
}> = [
  {
    action: 'attach',
    label: 'Attach UE(s)',
    description: 'Runs attach_ue.sh generated by the UE creation script.',
    tone: 'primary',
  },
  {
    action: 'detach',
    label: 'Detach UE(s)',
    description: 'Runs dettach_ue.sh to delete UE deployments and configmaps.',
    tone: 'ghost',
    confirmText: 'Detach all generated UE deployments from the cluster?',
  },
  {
    action: 'remove',
    label: 'Remove UE(s)',
    description: 'Runs remove_ue.sh to delete subscribers and generated UE folders.',
    tone: 'danger',
    confirmText: 'Remove all generated UE subscribers and generated script folders?',
  },
  {
    action: 'traffic',
    label: 'Run Traffic Test',
    description: 'Runs traffic_ue.sh to ping through UE tunnel interfaces.',
    tone: 'ghost',
  },
  {
    action: 'check',
    label: 'Check UE(s)',
    description: 'Runs check_ue.sh to report registration and PDU session outcome.',
    tone: 'ghost',
  },
];

//The same four operations, scoped to one UE. Order follows the lifecycle: bring it
//up, prove it works, take it down, delete it.
const PER_UE_ACTIONS: Array<{
  action: K8sUeScriptAction;
  label: string;
  title: string;
  tone: 'primary' | 'danger' | 'ghost';
  confirm?: (imsi: string) => string;
  /** States the action is allowed in. Undefined means any state. */
  requires?: SubscriberUeState[];
  /** Shown instead of `title` when the state does not allow it. */
  blocked?: string;
}> = [
  { action: 'attach', label: 'Attach', title: 'Create this UE\u2019s configmap and deployment', tone: 'primary' },
  {
    action: 'traffic',
    label: 'Traffic',
    title: 'Ping through this UE\u2019s tunnels and watch the output',
    tone: 'ghost',
    //No uesimtun device exists until the UE has registered
    requires: ['attached'],
    blocked: 'Attach this UE first \u2014 traffic needs a registered UE',
  },
  { action: 'check', label: 'Check', title: 'Registration and PDU session outcome for this UE', tone: 'ghost' },
  {
    action: 'detach',
    label: 'Detach',
    title: 'Delete this UE\u2019s deployment and configmap, keeping its subscriber',
    tone: 'ghost',
    confirm: (imsi) => `Detach UE ${imsi} from the cluster? Its subscriber stays provisioned.`,
  },
  {
    action: 'remove',
    //Named to match the Subscribers page: one delete, and it takes the files and
    //the subscriber entry together
    label: 'Delete UE',
    title: 'Delete this UE\u2019s staged files and its subscriber entry',
    tone: 'danger',
    //Deleting a UE that is still on the air would pull it out from under a live
    //registration, so detach comes first
    requires: ['detached', 'unconfigured'],
    blocked: 'Detach this UE first \u2014 only a detached UE can be deleted',
    confirm: (imsi) => `Delete UE ${imsi}? Its staged files and subscriber entry both go.`,
  },
];

//Status reports UEs by folder name; the scripts and the API select on the IMSI
function ueImsi(folder: string): string {
  return folder.replace(/^ue/i, '');
}

//Whether this UE's state permits the action, and what to say when it does not
function ueGate(
  item: { title: string; requires?: SubscriberUeState[]; blocked?: string },
  status?: SubscriberUeStatus,
): { allowed: boolean; reason: string } {
  if (!item.requires) {
    return { allowed: true, reason: item.title };
  }
  if (!status) {
    return { allowed: false, reason: 'Waiting for this UE\u2019s state' };
  }
  return item.requires.includes(status.status)
    ? { allowed: true, reason: item.title }
    : { allowed: false, reason: item.blocked ?? item.title };
}

function buttonClass(tone: 'primary' | 'danger' | 'ghost'): string {
  if (tone === 'primary') return 'nms-btn-primary';
  if (tone === 'danger') return 'nms-btn-danger';
  return 'nms-btn-ghost';
}

export function K8sLabPage(): JSX.Element {
  const [status, setStatus] = useState<K8sLabStatus | null>(null);
  const [commands, setCommands] = useState<K8sCommandDefinition[]>([]);
  const [logs, setLogs] = useState<string[]>([]);
  const [selectedLog, setSelectedLog] = useState<string>('');
  const [logFile, setLogFile] = useState<K8sLogFile | null>(null);
  const [labAction, setLabAction] = useState<string | null>(null);
  const [ueAction, setUeAction] = useState<string | null>(null);
  const [ueCount, setUeCount] = useState(1);
  const [ueScenario, setUeScenario] = useState<K8sUeScenario>('normal');
  const [lastResult, setLastResult] = useState<K8sScriptResult | null>(null);
  //Staged UEs carry no state of their own, so the buttons that depend on it read
  //the same status the Subscribers page uses
  const [ueStatuses, setUeStatuses] = useState<Record<string, SubscriberUeStatus>>({});
  const [trafficImsi, setTrafficImsi] = useState<string | null>(null);

  const loadStatus = async (preferredLog?: string) => {
    try {
      const [statusData, commandData, logFiles] = await Promise.all([
        k8sApi.getStatus(),
        k8sApi.listCommands(),
        k8sApi.listLogs(),
      ]);

      setStatus(statusData);
      setCommands(commandData);
      setLogs(logFiles);

      const nextLog = preferredLog || selectedLog || logFiles[0] || '';
      if (nextLog) {
        setSelectedLog(nextLog);
        const latest = await k8sApi.getLog(nextLog);
        setLogFile(latest);
      } else {
        setSelectedLog('');
        setLogFile(null);
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      toast.error(`Failed to load K8s lab status: ${message}`);
    }
  };

  const commandAvailable = (id: string) =>
    commands.some((command) => command.id === id && command.available);

  const showScriptResult = (result: K8sScriptResult) => {
    setLastResult(result);
    if (result.success) {
      toast.success(result.message);
    } else {
      toast.error(result.message);
    }
  };

  useEffect(() => {
    loadStatus();
    // We only need this on first render.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const refreshLog = async (name: string) => {
    try {
      setSelectedLog(name);
      const file = await k8sApi.getLog(name);
      setLogFile(file);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      toast.error(`Failed to read log: ${message}`);
    }
  };

  const runLabAction = async (
    action: K8sLabAction,
    confirmText?: string,
  ) => {
    if (confirmText && !window.confirm(confirmText)) {
      return;
    }

    setLabAction(action);
    try {
      const result = await k8sApi.runAction(action);
      showScriptResult(result);
      await loadStatus(result.logFiles[0]);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      toast.error(`Failed to run ${action}: ${message}`);
    } finally {
      setLabAction(null);
    }
  };

  const createUes = async () => {
    setUeAction('create');
    try {
      const result = await k8sApi.createUes(ueCount, ueScenario);
      showScriptResult(result);
      await loadStatus(result.logFiles[0]);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      toast.error(`Failed to create UE scripts: ${message}`);
    } finally {
      setUeAction(null);
    }
  };

  //Refresh the per-UE state after the staged set changes or an action runs
  const stagedKey = (status?.generatedUes || []).join(',');
  useEffect(() => {
    const imsis = (status?.generatedUes || []).map(ueImsi);
    if (imsis.length === 0) {
      setUeStatuses({});
      return;
    }

    let cancelled = false;
    (async () => {
      try {
        const statuses = await subscriberApi.getUeStatuses(imsis);
        if (!cancelled) {
          setUeStatuses(Object.fromEntries(statuses.map((entry) => [entry.imsi, entry])));
        }
      } catch {
        //A status we cannot read leaves the guarded buttons disabled, which is the
        //safe way round; the unguarded ones keep working
        if (!cancelled) {
          setUeStatuses({});
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [stagedKey]);

  const runUeAction = async (
    action: K8sUeScriptAction,
    confirmText?: string,
    imsis?: string[],
  ) => {
    if (confirmText && !window.confirm(confirmText)) {
      return;
    }

    //One UE at a time: the scripts hold a mutex on the backend anyway, and this
    //keeps the button that was pressed the one that shows as running
    const busyKey = imsis?.length ? `${action}:${imsis[0]}` : action;
    setUeAction(busyKey);
    try {
      const result = await k8sApi.runUeAction(action, imsis);
      showScriptResult(result);
      await loadStatus(result.logFiles[0]);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      const scope = imsis?.length ? ` on ${imsis.join(', ')}` : '';
      toast.error(`Failed to run UE action "${action}"${scope}: ${message}`);
    } finally {
      setUeAction(null);
    }
  };

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold font-display">K8s Lab</h1>
          <p className="text-sm text-nms-text-dim mt-1">
            Run the sibling `laas-5gsa-k8s-1` automation scripts from the GUI.
          </p>
        </div>
        <button
          onClick={() => loadStatus()}
          className="nms-btn-ghost flex items-center gap-2"
        >
          <RefreshCw className="w-4 h-4" /> Refresh
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">
        <div className="nms-card">
          <div className="flex items-center gap-2 mb-2 text-nms-accent">
            <Server className="w-4 h-4" />
            <span className="text-sm font-semibold font-display">Repo Path</span>
          </div>
          <div className="text-xs font-mono break-all text-nms-text">{status?.rootPath || 'Loading...'}</div>
          <div className="mt-2 text-xs text-nms-text-dim">
            Host user: <span className="font-mono text-nms-text">{status?.executionUser || '—'}</span>
          </div>
          <div className="mt-3 text-xs">
            <span className={status?.available ? 'text-nms-green' : 'text-nms-red'}>
              {status?.available ? 'Available' : 'Missing'}
            </span>
          </div>
        </div>

        <div className="nms-card">
          <div className="flex items-center gap-2 mb-2 text-nms-accent">
            <Wrench className="w-4 h-4" />
            <span className="text-sm font-semibold font-display">Kubectl</span>
          </div>
          <div className="text-xs text-nms-text-dim">Context</div>
          <div className="text-sm font-mono text-nms-text">{status?.currentContext || '—'}</div>
          <div className="mt-3 text-xs">
            <span className={status?.kubectlAvailable ? 'text-nms-green' : 'text-nms-red'}>
              {status?.kubectlAvailable ? 'Installed' : 'Unavailable'}
            </span>
          </div>
        </div>

        <div className="nms-card">
          <div className="flex items-center gap-2 mb-2 text-nms-accent">
            <Wifi className="w-4 h-4" />
            <span className="text-sm font-semibold font-display">Cluster</span>
          </div>
          <div className="text-xs text-nms-text-dim">Namespace</div>
          <div className="text-sm font-mono text-nms-text">{status?.open5gsNamespace ? 'open5gs' : '—'}</div>
          <div className="mt-3 text-xs">
            <span className={status?.clusterReachable ? 'text-nms-green' : 'text-nms-red'}>
              {status?.clusterReachable ? 'Reachable' : 'Not reachable'}
            </span>
          </div>
        </div>

        <div className="nms-card">
          <div className="flex items-center gap-2 mb-2 text-nms-accent">
            <Terminal className="w-4 h-4" />
            <span className="text-sm font-semibold font-display">Open5GS Pods</span>
          </div>
          <div className="text-3xl font-semibold font-display text-nms-text">
            {status?.open5gsReadyPodCount ?? 0}
            <span className="text-base text-nms-text-dim"> / {status?.open5gsPodCount ?? 0}</span>
          </div>
          <div className="text-xs text-nms-text-dim mt-1">ready / total</div>
          <div className="mt-3 text-xs text-nms-text-dim">
            Generated UE folders: {status?.generatedUes.length ?? 0}
          </div>
        </div>
      </div>

      {(status?.open5gsUnhealthyPods.length ?? 0) > 0 && (
        <div className="rounded-lg border border-amber-500/20 bg-amber-500/10 p-4 text-xs text-amber-200">
          <div className="flex items-start gap-2">
            <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
            <div>
              <div className="font-semibold mb-1">The lab has unhealthy pods</div>
              <div className="font-mono break-all">{status?.open5gsUnhealthyPods.join(', ')}</div>
            </div>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
        <div className="nms-card space-y-4">
          <div>
            <h2 className="text-lg font-semibold font-display">Lab Actions</h2>
            <p className="text-sm text-nms-text-dim mt-1">
              These buttons execute the original host scripts from the sibling repository.
            </p>
          </div>

          <div className="space-y-3">
            {LAB_ACTIONS.map((item) => (
              <div
                key={item.action}
                className="border border-nms-border rounded-lg p-4 bg-nms-surface-2/40"
              >
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <div className="text-sm font-semibold text-nms-text">{item.label}</div>
                    <div className="text-xs text-nms-text-dim mt-1">{item.description}</div>
                  </div>
                  <button
                    onClick={() => runLabAction(item.action, item.confirmText)}
                    disabled={labAction !== null || !commandAvailable(item.action)}
                    className={`${buttonClass(item.tone)} flex items-center gap-2 shrink-0`}
                  >
                    {item.action.includes('stop') || item.action.includes('delete') ? (
                      <Square className="w-4 h-4" />
                    ) : (
                      <Play className="w-4 h-4" />
                    )}
                    {labAction === item.action ? 'Running...' : item.label}
                  </button>
                </div>
              </div>
            ))}
          </div>

          <div className="rounded-lg border border-amber-500/20 bg-amber-500/10 p-3 text-xs text-amber-200">
            <div className="flex items-start gap-2">
              <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
              <div>
                `install-node` and `delete-node` change host packages and networking. Use them only on the intended VM.
              </div>
            </div>
          </div>
        </div>

        <div className="nms-card space-y-4">
          <div>
            <h2 className="text-lg font-semibold font-display">UE Scripts</h2>
            <p className="text-sm text-nms-text-dim mt-1">
              Create and execute the generated UE scripts from `SCRIPTS/`.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <div>
              <label className="nms-label">UE Count</label>
              <input
                type="number"
                min={1}
                max={50}
                value={ueCount}
                onChange={(e) => setUeCount(Math.max(1, Math.min(50, parseInt(e.target.value || '1', 10))))}
                className="nms-input"
              />
            </div>
            <div>
              <label className="nms-label">Scenario</label>
              <select
                value={ueScenario}
                onChange={(e) => setUeScenario(e.target.value as K8sUeScenario)}
                className="nms-input"
              >
                {SCENARIO_OPTIONS.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <button
            onClick={createUes}
            disabled={ueAction !== null || !commandAvailable(`create-ues:${ueScenario}`)}
            className="nms-btn-primary flex items-center gap-2"
          >
            <Zap className="w-4 h-4" />
            {ueAction === 'create' ? 'Creating...' : 'Create UE(s)'}
          </button>
          <div className="text-xs text-nms-text-dim font-mono">
            {commands.find((command) => command.id === `create-ues:${ueScenario}`)?.script}
          </div>

          <div className="divide-y divide-nms-border rounded-lg border border-nms-border overflow-hidden">
            {(status?.generatedUes || []).map((ue) => {
              const imsi = ueImsi(ue);
              return (
                <div
                  key={ue}
                  className="flex flex-wrap items-center justify-between gap-3 px-3 py-2 bg-nms-surface-2/30"
                >
                  <span className="font-mono text-xs text-nms-accent">{imsi}</span>
                  <div className="flex flex-wrap items-center gap-1.5">
                    <span className="mr-1 text-xs text-nms-text-dim">
                      {ueStatuses[imsi]?.status ?? 'unknown'}
                    </span>
                    {PER_UE_ACTIONS.map((item) => {
                      const gate = ueGate(item, ueStatuses[imsi]);
                      return (
                        <button
                          key={item.action}
                          onClick={() =>
                            item.action === 'traffic'
                              ? setTrafficImsi(imsi)
                              : runUeAction(item.action, item.confirm?.(imsi), [imsi])
                          }
                          disabled={
                            ueAction !== null ||
                            !commandAvailable(`ue-${item.action}`) ||
                            !gate.allowed
                          }
                          className={`${buttonClass(item.tone)} px-2 py-1 text-xs`}
                          title={gate.reason}
                        >
                          {ueAction === `${item.action}:${imsi}` ? '...' : item.label}
                        </button>
                      );
                    })}
                  </div>
                </div>
              );
            })}
            {status?.generatedUes.length === 0 && (
              <div className="px-3 py-2 text-xs text-nms-text-dim">
                No staged UEs yet. Create one above.
              </div>
            )}
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {UE_ACTIONS.map((item) => (
              <button
                key={item.action}
                onClick={() => runUeAction(item.action, item.confirmText)}
                disabled={ueAction !== null || !commandAvailable(`ue-${item.action}`)}
                className={`${buttonClass(item.tone)} flex items-center justify-center gap-2`}
                title={item.description}
              >
                {item.action === 'remove' ? (
                  <Trash2 className="w-4 h-4" />
                ) : item.action === 'traffic' ? (
                  <Wifi className="w-4 h-4" />
                ) : item.action === 'detach' ? (
                  <Square className="w-4 h-4" />
                ) : (
                  <Play className="w-4 h-4" />
                )}
                {ueAction === item.action ? 'Running...' : item.label}
              </button>
            ))}
          </div>

          <div className="rounded-lg border border-nms-border bg-nms-surface-2/40 p-3 text-xs text-nms-text-dim">
            The buttons run the generated `attach_ue.sh`, `dettach_ue.sh`, `remove_ue.sh`, `traffic_ue.sh` and `check_ue.sh` files in the sibling repo. The buttons on a UE row pass that UE's IMSI to the same script, so it acts on that UE alone; the buttons below act on every staged UE.
          </div>
        </div>
      </div>

      <div className="nms-card">
        <div className="mb-4">
          <h2 className="text-lg font-semibold font-display">Script Command Map</h2>
          <p className="text-sm text-nms-text-dim mt-1">
            Every supported script and the GUI control that executes it.
          </p>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="text-nms-text-dim border-b border-nms-border">
              <tr>
                <th className="py-2 pr-4 font-medium">GUI action</th>
                <th className="py-2 pr-4 font-medium">Script</th>
                <th className="py-2 pr-4 font-medium">Purpose</th>
                <th className="py-2 font-medium">Status</th>
              </tr>
            </thead>
            <tbody>
              {commands.map((command) => (
                <tr key={command.id} className="border-b border-nms-border/60 last:border-0">
                  <td className="py-3 pr-4 text-nms-text">{command.guiAction}</td>
                  <td className="py-3 pr-4 font-mono text-nms-accent whitespace-nowrap">
                    {command.script}{command.acceptsUeCount ? ' <count>' : ''}
                  </td>
                  <td className="py-3 pr-4 text-nms-text-dim">{command.description}</td>
                  <td className={`py-3 ${command.available ? 'text-nms-green' : 'text-nms-red'}`}>
                    {command.available ? 'Available' : 'Missing'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-[320px_1fr] gap-6">
        <div className="nms-card space-y-3">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold font-display">Logs</h2>
            <ShieldAlert className="w-4 h-4 text-nms-text-dim" />
          </div>

          <div className="space-y-2 max-h-[420px] overflow-y-auto">
            {logs.map((name) => (
              <button
                key={name}
                onClick={() => refreshLog(name)}
                className={`w-full text-left px-3 py-2 rounded text-xs font-mono border ${
                  selectedLog === name
                    ? 'bg-nms-accent/10 text-nms-accent border-nms-accent/30'
                    : 'bg-nms-surface-2/30 text-nms-text-dim border-nms-border hover:text-nms-text'
                }`}
              >
                {name}
              </button>
            ))}
            {logs.length === 0 && (
              <div className="text-xs text-nms-text-dim">No log files found in `LOGS/` yet.</div>
            )}
          </div>
        </div>

        <div className="nms-card">
          <div className="flex items-center justify-between mb-3">
            <div>
              <h2 className="text-lg font-semibold font-display">Log Output</h2>
              <p className="text-xs text-nms-text-dim mt-1">{selectedLog || 'Select a log file'}</p>
            </div>
            {selectedLog && (
              <button onClick={() => refreshLog(selectedLog)} className="nms-btn-ghost text-xs flex items-center gap-2">
                <RefreshCw className="w-3.5 h-3.5" /> Reload Log
              </button>
            )}
          </div>

          <pre className="bg-nms-bg rounded-lg border border-nms-border p-4 text-xs text-nms-text-dim overflow-auto max-h-[520px] whitespace-pre-wrap break-words font-mono">
            {logFile?.content || 'No log loaded.'}
          </pre>
        </div>
      </div>

      {lastResult && (
        <div className="nms-card">
          <div className="flex items-center justify-between gap-3 mb-3">
            <div>
              <h2 className="text-lg font-semibold font-display">Last Script Result</h2>
              <p className="text-xs text-nms-text-dim mt-1">{lastResult.action}</p>
            </div>
            <span className={lastResult.success ? 'text-nms-green text-sm' : 'text-nms-red text-sm'}>
              {lastResult.success ? 'Success' : 'Failed'}
            </span>
          </div>

          <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
            <div>
              <div className="text-xs font-semibold text-nms-text mb-2">STDOUT</div>
              <pre className="bg-nms-bg rounded-lg border border-nms-border p-4 text-xs text-nms-text-dim overflow-auto max-h-80 whitespace-pre-wrap break-words font-mono">
                {lastResult.stdout || 'No stdout output.'}
              </pre>
            </div>
            <div>
              <div className="text-xs font-semibold text-nms-text mb-2">STDERR</div>
              <pre className="bg-nms-bg rounded-lg border border-nms-border p-4 text-xs text-nms-text-dim overflow-auto max-h-80 whitespace-pre-wrap break-words font-mono">
                {lastResult.stderr || 'No stderr output.'}
              </pre>
            </div>
          </div>
        </div>
      )}

      <UeTrafficMonitor
        imsi={trafficImsi}
        onClose={() => {
          setTrafficImsi(null);
          void loadStatus();
        }}
      />
    </div>
  );
}
